version: '3'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__TELEMETRY_ENABLED=false
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local 